include: package:flutter_lints/flutter.yaml

linter:
  rules:
    -prefer_relative_imports
    -prefer_const_constructors
    -prefer_const_declarations
    -prefer_const_literals_to_create_immutables
    -Unnecessary_const

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore
