include: package:lint/analysis_options.yaml

linter:
  rules:
    -prefer_relative_imports

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore
