name: owl_chat
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.6

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  anim_search_bar: ^2.0.2
  animations: ^2.0.2
  auto_animated: ^3.0.1
  auto_direction: ^0.0.5
  awesome_notifications: ^0.6.21
  bloc: ^8.0.2
  bloc_concurrency: ^0.2.0
  bloc_test: ^9.0.2
  built_collection: ^5.1.1
  cached_network_image: ^3.1.0
  cloud_firestore: ^3.1.6
  cloud_firestore_odm: ^1.0.0-dev.5
  collection: ^1.15.0
  connectivity_plus: ^2.1.0
  cropperx: ^1.0.0
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: ^1.2.2
  dartz: ^0.10.1
  easy_localization: ^3.0.0
  emoji_picker_flutter: ^1.0.7
  equatable: ^2.0.3
  faker: ^2.0.0
  firebase: ^9.0.1
  firebase_app_installations: ^0.1.0+5
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5
  firebase_messaging: ^11.2.5
  firebase_remote_config: ^1.0.4
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_bloc: ^0.29.3
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  fluttertoast: any
  font_awesome_flutter: ^9.1.0
  freezed: ^1.0.0
  getwidget: ^2.0.4
  giphy_get: ^2.0.3
  go_router: ^3.0.1
  google_fonts: ^2.1.0
  hive: ^2.0.5
  http: ^0.13.4
  hydrated_bloc: ^8.0.0
  image_picker: ^0.8.4
  implicitly_animated_reorderable_list: ^0.4.2
  intl: ^0.17.0
  isolator: ^2.0.2
  json_annotation: ^4.3.0
  line_awesome_flutter: any
  line_awesome_icons: ^1.0.4+2
  line_icons: ^2.0.1
  loading_animations: ^2.2.0
  material_floating_search_bar: ^0.3.4
  package_info: ^2.0.2
  path_provider: ^2.0.8
  provider: ^6.0.0
  r_upgrade: ^0.3.6
  rounded_loading_button: ^2.0.3
  rxdart: ^0.27.3
  scrollable_positioned_list: ^0.2.3
  shared_preferences: ^2.0.12
  show_up_animation: ^2.0.0
  upgrader: ^3.11.0
  version: ^2.0.0

dev_dependencies:
  build_runner: null
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  json_serializable: ^6.1.3
  lint: ^1.0.0
  test: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/google_fonts/
    - assets/
    - assets/icons/


